### ISSUE TITLE
JIRA Update - Not all JIRA issues have custom Flags

### ISSUE THREAD

**Issue by ryanemerson** [ryanemerson/aphrodite#4]
For example JBEAP issues have the field "customfield_12311242" which is for PM_ACK, however Wildfly issues do not have this field.  This means that an update to a WFLY issue will fail with a JiraException if the PM_ACK flag is set; as the required custom field is not in the editmeta JSON object returned by Jira.  

Not an issue for core issues, i.e. EAP7, however it may cause issues when trying to interact with components.

**Comment by elguardian** [comment]
Hi ryan. The behaviour should not be like this IMO. I think we must specify a default behaviour in this case because sooner or later they will have to introduce way to include the stream information in the JIRA. 3-ack system is not going to change soon.
I think the default behaviour should be to set the stream to the first one 7.0.z otherwise this project will loose its strong point.
